// Code generated by hertz generator.

package show

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _essayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _essayevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getevaluatelogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ocrMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applysignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _doexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _simpleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsimpleexercisesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeexerciseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeevaluateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dailyattendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _invitationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinvitationcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fillinvitationcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _daily_attendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdailyattendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}
