// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/essay-show/biz/application/service"
	"github.com/xh-polaris/essay-show/biz/infrastructure/config"
	"github.com/xh-polaris/essay-show/biz/infrastructure/mapper/log"
	"github.com/xh-polaris/essay-show/biz/infrastructure/mapper/user"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mongoMapper := user.NewMongoMapper(configConfig)
	userService := service.UserService{
		UserMapper: mongoMapper,
	}
	logMongoMapper := log.NewMongoMapper(configConfig)
	essayService := service.EssayService{
		LogMapper:  logMongoMapper,
		UserMapper: mongoMapper,
	}
	providerProvider := &Provider{
		Config:       configConfig,
		UserService:  userService,
		EssayService: essayService,
	}
	return providerProvider, nil
}
